spring.application.name=suaraRakyat

server.port = 8090
spring.jpa.show-sql=true
spring.datasource.url=jdbc:sqlserver://localhost:1433;encrypt=true;trustServerCertificate=true;databaseName=SuaraRakyat
spring.datasource.username=sa
spring.datasource.password=H1r2t3_08
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServer2012Dialect
spring.jpa.hibernate.ddl-auto=update


# JWT Properties
suaraRakyat.app.jwtSecret=supersecretjwtkeythatisatleast256bitslongandsecure
suaraRakyat.app.jwtExpirationMs=86400000

# API Key
app.api-key=SuaraRakyatTejaTanra
