spring.application.name=suaraRakyat

server.port = 8090
spring.jpa.show-sql=true
spring.datasource.url=spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=
spring.datasource.username=sa
spring.datasource.password=H1r2t3_08
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

